config/routes.rb
TraineoLogger::Application.routes.draw do

  root :to => 'logger#login'
  
  resources :logger
  get '/auth/:provider/callback' => 'login#callback'
  get '/logout' => 'login#logout', :as => 'logout'
  get '/oauth_failure' => 'login#oauth_failure'

  match '/logindex' => 'logger#index', :as => :logindex
  match '/log' => 'logger#log', :as => :log
  match '/manual_log' => 'logger#manual_log'
  match '/:page' => 'logger#index', :as => :logger_index

end

app/models/traineo.rb
class Traineo
  def initialize
    @agent = Mechanize.new

    # Login
    @page = @agent.get 'http://traineo.com/login'
    form = @page.form
    form.send("user[username]", Rails.application.config.traineo_username)
    form.send("user[password]", Rails.application.config.traineo_password)
    page = @agent.submit(form)

    # Get weight page and submit
    @page = @agent.get 'http://traineo.com/weight'
    @form = @page.form
  end

  def log(date, weight)
    @form.date = date
    @form.weight_input = weight

    page = @agent.submit(@form)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/logger_controller.rb
require 'date'

class LoggerController < ApplicationController

  def initialize

    config = {
        :username =>  Rails.application.config.evernote_username,
        :password => Rails.application.config.evernote_password,
        :consumer_key => Rails.application.config.evernote_key,
        :consumer_secret => Rails.application.config.evernote_secret
    }



    # client = EvernoteOAuth::Client.new(
    #   :consumer_key => config.consumer_key,
    #   :consumer_secret => config.consumer_secret,
    #   :sandbox => true
    # )
    # @auth_token = "S=s38:U=3e8fa6:E=14392fb3221:C=13c3b4a0621:P=1cd:A=en-devtoken:H=e0dc3bc1a9cf7d73de357385c18a2552"
    # # @user_store = EvernoteOAuth::Client.new(:token => token).user_store
    # # user = @user_store.getUser()
    # @client = EvernoteOAuth::Client.new(:token => @auth_token)
    # puts @client.note_store
    # @note_store = EvernoteOAuth::Client.new(:token => @auth_token).note_store

  end

  def login
  end

  def index
    token = session[:authtoken]
    client = EvernoteOAuth::Client.new(:token => token)
    @note_store = client.note_store

    page = params[:page] || 1
    @next_page = page.to_i + 1
    @prev_page = page.to_i - 1

    if @prev_page == 0 then
      @prev_page = 1
    end

    @per_page = Rails.application.config.notes_per_page

    @notebooks = @note_store.listNotebooks
    @found = "Found #{@notebooks.size} notebooks:"

    default_notebook = nil
    @notebooks.each do |notebook|
      if notebook.name == "Weight"
        default_notebook = notebook
      end
    end

    filter = Evernote::EDAM::NoteStore::NoteFilter.new;
    filter.notebookGuid = default_notebook.guid
    filter.order = 1
    notes = @note_store.findNotes(filter, @per_page * (page.to_i-1), @per_page)
    notes.notes.each do |note|
      note.created = Time.at(note.created/1000).getlocal('+10:00').strftime("%B %-d, %Y %H:%M")
    end
    @notes = notes
    render :index, :layout => "application"
  end

  def log
    token = session[:authtoken]
    client = EvernoteOAuth::Client.new(:token => token)
    @note_store = client.note_store

    traineo = Traineo.new

    notes = params["notes"]
    @next_page = params["next_page"]

    @note_array = []
    notes.each do |note|
      retrieved_note = @note_store.getNote(note, false, false, false, false)
      date = Time.at(retrieved_note.created/1000).getlocal('+10:00').strftime("%B %-d, %Y")
      weight = retrieved_note.title.split(" ")[0].to_f
      weight = fixweight(weight)

      traineo.log date, weight

      @note_array << [date, weight]

    end
  end

  def manual_log
    agent = Mechanize.new

    # Login
    page = agent.get 'http://traineo.com/login'
    form = page.form
    form.send("user[username]", Rails.application.config.traineo_username)
    form.send("user[password]", Rails.application.config.traineo_password)
    page = agent.submit(form)

    # Get weight page and submit
    page = agent.get 'http://traineo.com/weight'
    form = page.form

    form.date = 'March 14, 2012'
    form.weight_input = '98.5'

    page = agent.submit(form)

    raise page.inspect
  end

  def fixweight(weight)
    return (weight > 130) ? fixweight(weight / 10) : weight
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  rescue_from OAuth::Unauthorized, :with => Proc.new{redirect_to root_path}

  def callback
    session[:authtoken] = request.env['omniauth.auth']['credentials']['token']
    redirect_to root_path
  end

  def oauth_failure
    redirect_to root_path
  end

  def logout
    session.clear
    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/logger_helper.rb
module LoggerHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Traineo Logger
    %meta{:charset => "utf-8"}
    %meta{"http-equiv" => "X-UA-Compatible", :content => "IE=edge,chrome=1"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    = stylesheet_link_tag :application, :media => "all"
    = javascript_include_tag :application
    = csrf_meta_tags
  %body
    #container.container
      %header
      #main{:role => "main"}
        = yield
      %footer

app/views/logger/index.html.haml
%h1 Hello
= @page
= @found
%br
%ol
  - @notebooks.each do |notebook|
    %li #{notebook.name}

%button{:id => "select-all"}
  Toggle
= form_tag log_path, :method => "post" do
  %ul
    - @notes.notes.each do |note|
      %li
        = check_box_tag "notes[]", "#{note.guid}", false, {:id => "notes_#{note.guid}", :class => "weight-check"}
        %label{:for => "notes_#{note.guid}"}
          %span.date
            #{note.created}
          %span.title
            #{note.title}
  %input{:type => 'submit'}
  %input{:type => 'hidden', :name => 'next_page', :value => @next_page}

= link_to "Previous #{@per_page}", logger_index_url(@prev_page)
= link_to "Next #{@per_page}", logger_index_url(@next_page)
%br
= link_to "Traineo Page", "http://traineo.com/weight"

%script{:type => "text/javascript"}
  :plain

    $().ready(function() {

      var clickEm = function() {
        $(".weight-check").each(function(idx, elem) {
          var toggle = !$(elem).prop('checked');
          $(elem).prop('checked', toggle);
        });
      }

      $('#select-all').click(function() {
        clickEm();
      });
    });

app/views/logger/log.html.haml
Log
%br
- @note_array.each do |note|
  = note.inspect
  %br
%br
%script{:type => "text/javascript"}
  var next_page = '#{logger_index_url(@next_page)}';
  :plain

      setTimeout(function() {
        document.location = next_page;
      }, 1000);

app/views/logger/login.html.haml
= link_to 'Login via Evernote', '/auth/evernote'

- if session[:authtoken]
    = link_to 'Start logging', '/logindex'